name: BenchmarkingClassifiers
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - biopython=1.81
  - click=8.1.7
  - jinja2=3.1.2
  - matplotlib=3.8.2
  - numpy=1.26.2
  - pandas=2.1.3
  - pyyaml=6.0.1
  - requests=2.31.0
  - rich=13.7.0
  - seaborn=0.13.0
  - scikit-learn=1.3.2
  - snakemake=7.32.4
  - pip
  - seqkit=2.3.1
  - taxonkit=0.15.0
  - sylph=0.8.0
  - 
  - pip:
      - pulp==2.7.0
